@@grammar::Forest
@@nameguard :: False

start
    =
    {statement}+
    ;

statement
    =
    | print
    | pop
    | value
    | dup
    | swap
    | add
    | sub
    | mul
    | mod
    | pow
    | div
    | if
    | equality
    | iterate
    ;

if
    =
    '?' statement else
    ;

else
    =
    '#' statement
    ;

equality
    =
    '='
    ;

iterate
    =
    'I' {statement}+ 'E'
    ;

pow
    =
    '^'
    ;

mod
    =
    '%'
    ;

add
    =
    '+'
    ;

sub
    =
    '-'
    ;

mul
    =
    '*'
    ;

div
    =
    '/'
    ;

dup
    =
    'U'
    ;

swap
    =
    'S'
    ;

print
    =
    '.'
    ;

pop
    =
    'O'
    ;

value
    =
    | number
    | string
    | boolean
    ;

boolean
    =
    | 'T'
    | 'F'
    ;

string
    =
    '"' letters '"'
    ;


number
    =
    'D' digits
    ;

digits
    =
    /[0-9]+/
    ;

letters
    =
    /[a-zA-Z ]+/
    ;
